### ISSUE TITLE
why got error "AttributeError: 'NoneType' object has no attribute 'hidden_size'"

### ISSUE THREAD

**Issue by hischen** [bert-nmt/bert-nmt#11]
The log is as follow:
0%|                                        | 33792/407873900 [00:29<94:07:20, 1203.63BModel name 'bert-base-uncased' was not found in model name list (bert-base-uncased, bert-large   -uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-mult   ilingual-cased, bert-base-chinese, bert-base-german-cased). We assumed 'https://s3.amazonaw   s.com/models.huggingface.co/bert/bert-base-uncased.tar.gz' was a path or url but couldn't f   ind any file associated to this path or url.
Traceback (most recent call last):
Namespace(activation_dropout=0.0, activation_fn='relu', adam_betas='(0.9,0.98)', adam_eps=1   e-08, adaptive_input=False, adaptive_softmax_cutoff=None, adaptive_softmax_dropout=0, arch=   'transformer_s2_iwslt_de_en', attention_dropout=0.0, bert_first=True, bert_gates=[1, 1, 1,    1, 1, 1], bert_model_name='bert-base-uncased', bert_output_layer=-1, bert_ratio=1.0, bucket   _cap_mb=25, clip_norm=25, cpu=False, criterion='label_smoothed_cross_entropy', curriculum=0   , data='data-bin/iwslt14.tokenized.de-en', dataset_impl='cached', ddp_backend='c10d', decod   er_attention_heads=4, decoder_embed_dim=512, decoder_embed_path=None, decoder_ffn_embed_dim   =1024, decoder_input_dim=512, decoder_layers=6, decoder_learned_pos=False, decoder_no_bert=   False, decoder_normalize_before=False, decoder_output_dim=512, device_id=0, disable_validat   ion=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=F   alse, distributed_port=-1, distributed_rank=0, distributed_world_size=1, dropout=0.3, encod   er_attention_heads=4, encoder_bert_dropout=True, encoder_bert_dropout_ratio=0.5, encoder_be   rt_mixup=False, encoder_embed_dim=512, encoder_embed_path=None, encoder_ffn_embed_dim=1024,    encoder_layers=6, encoder_learned_pos=False, encoder_normalize_before=False, encoder_ratio   =1.0, find_unused_parameters=False, finetune_bert=False, fix_batches_to_gpus=False, fp16=Fa   lse, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, keep_interval_u   pdates=-1, keep_last_epochs=-1, label_smoothing=0.1, lazy_load=False, left_pad_source='True   ', left_pad_target='False', log_format=None, log_interval=1000, lr=[0.0005], lr_scheduler='   inverse_sqrt', mask_cls_sep=False, max_epoch=0, max_sentences=None, max_sentences_valid=Non   e, max_source_positions=1024, max_target_positions=1024, max_tokens=50000, max_update=15000   0, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=1e-09, no_epoch_checkpoints=F   alse, no_progress_bar=False, no_save=False, no_token_positional_embeddings=False, num_worke   rs=0, optimizer='adam', optimizer_overrides='{}', raw_text=False, required_batch_size_multi   ple=8, reset_dataloader=False, reset_lr_scheduler=True, reset_meters=False, reset_optimizer   =False, restore_file='checkpoint_last.pt', save_dir='checkpoints/iwed_en_de_0.5', save_inte   rval=1, save_interval_updates=0, seed=1, sentence_avg=False, share_all_embeddings=True, sha   re_decoder_input_output_embed=False, skip_invalid_size_inputs_valid_test=False, source_lang   ='en', target_lang='de', task='translation', tbmf_wrapper=False, tensorboard_logdir='', thr   eshold_loss_scale=None, train_subset='train', update_freq=[1], upsample_primary=1, user_dir   =None, valid_subset='valid', validate_interval=1, warmup_from_nmt=True, warmup_init_lr=1e-0   7, warmup_nmt_file='checkpoint_nmt.pt', warmup_updates=4000, weight_decay=0.0001)
| [en] dictionary: 10152 types
| [de] dictionary: 10152 types
| data-bin/iwslt14.tokenized.de-en valid en-de 7283 examples
  File "train.py", line 315, in <module>
    cli_main()
  File "train.py", line 311, in cli_main
    main(args)
  File "train.py", line 49, in main
    model = task.build_model(args)
  File "/home/alex/bert-nmt-master/fairseq/tasks/fairseq_task.py", line 169, in build_mod   el
    return models.build_model(args, self)
  File "/home/alex/bert-nmt-master/fairseq/models/__init__.py", line 50, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
  File "/home/alex/bert-nmt-master/fairseq/models/transformer.py", line 301, in build_mod   el
    args.bert_out_dim = bertencoder.hidden_size
AttributeError: 'NoneType' object has no attribute 'hidden_size'
  0%|                                       | 33792/407873900 [05:15<1058:16:27, 107.05B/s]
pls help me,thanks

**Comment by bert-nmt** [comment]
From
```
0%| | 33792/407873900 [00:29<94:07:20, 1203.63BModel name 'bert-base-uncased' was not found in model name list (bert-base-uncased, bert-large -uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-mult ilingual-cased, bert-base-chinese, bert-base-german-cased). We assumed 'https://s3.amazonaw s.com/models.huggingface.co/bert/bert-base-uncased.tar.gz' was a path or url but couldn't f ind any file associated to this path or url.
```
---------------------------------------
It seems that you have not downloaded the BERT pre-trained model successfully, and this may be caused by your network.
