### ISSUE TITLE
BERT-NMT generation hangs and is killed unexpectedly

### ISSUE THREAD

**Issue by ShreyaKhurana** [bert-nmt/bert-nmt#19]
I preprocess my data for `bert-base-uncased` and I used the `transformer_iwslt_de_en` architecture to train the vanilla NMT using the following command:

```
CUDA_VISIBLE_DEVICES=0 fairseq-train \
    data-bin/sample \
    --arch transformer_iwslt_de_en --share-decoder-input-output-embed \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
    --dropout 0.3 --weight-decay 0.0001 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --max-tokens 4096 \
    --best-checkpoint-metric bleu --maximize-best-checkpoint-metric
```

Then I tried to train the BERT-fused NMT using:

```
python train.py $DATAPATH \
    -a $ARCH --optimizer adam --lr 0.0005 -s $src -t $tgt --label-smoothing 0.1 \
    --dropout 0.3 --max-tokens 4000 --min-lr '1e-09' --lr-scheduler inverse_sqrt --weight-decay 0.0001 \
    --criterion label_smoothed_cross_entropy --max-update 150000 --warmup-updates 4000 --warmup-init-lr '1e-07' \
    --adam-betas '(0.9,0.98)' --save-dir $SAVEDIR $warmup \
    --cpu --encoder-bert-dropout --encoder-bert-dropout-ratio $bedropout | tee -a $SAVEDIR/training.log
```

Training is successful and I see the trained model checkpoint. But when I tried to use generate.py using this:

```
python generate.py data-bin/sample \
    --path checkpoints/sample_iwslt_input_output_0.5/checkpoint293.pt --bert-model-name bert-base-uncased \
    --beam 5 --remove-bpe --cpu
```

Generation hangs indefinitely and when I stop it forcefully I get the following error stack:
```
^CTraceback (most recent call last):
  File "generate.py", line 195, in <module>
    cli_main()
  File "generate.py", line 191, in cli_main
    main(args)
  File "generate.py", line 109, in main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/home/skhurana/bert-nmt/fairseq/tasks/fairseq_task.py", line 246, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/skhurana/bert-nmt/venv/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/skhurana/bert-nmt/fairseq/sequence_generator.py", line 329, in generate
    tokens[:, :step + 1], encoder_outs, bert_outs, temperature=self.temperature,
  File "/home/skhurana/bert-nmt/venv/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/skhurana/bert-nmt/fairseq/sequence_generator.py", line 596, in forward_decoder
    temperature=temperature,
  File "/home/skhurana/bert-nmt/fairseq/sequence_generator.py", line 626, in _decode_one
    decoder_out = list(model.decoder(tokens, encoder_out, bert_out, incremental_state=self.incremental_states[model]))
  File "/home/skhurana/bert-nmt/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/skhurana/bert-nmt/fairseq/models/transformer.py", line 855, in forward
    x, extra = self.extract_features(prev_output_tokens, encoder_out, bert_encoder_out, incremental_state)
  File "/home/skhurana/bert-nmt/fairseq/models/transformer.py", line 904, in extract_features
    self_attn_mask=self.buffered_future_mask(x) if incremental_state is None else None,
  File "/home/skhurana/bert-nmt/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/skhurana/bert-nmt/fairseq/models/transformer.py", line 1511, in forward
    attn_mask=self_attn_mask,
  File "/home/skhurana/bert-nmt/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/skhurana/bert-nmt/fairseq/modules/multihead_attention.py", line 163, in forward
    v = torch.cat((prev_value, v), dim=1)
KeyboardInterrupt
```
Not sure what is happening.

Does the version of fairseq matter if it's different in training the vanilla NMT and the one used here?

**Comment by teslacool** [comment]
1. The version difference between the vanilla Fairseq and BERTNMT is indeed important, because there would be incompatibilities in state_dict used to load checkpoint when training BERTNMT. But this is not your problem, because you encountered this issue when using checkpoint that BERTNMT saved for generation.
2. You should set `--batch-size`  when inference, otherwise this will load all the sentence in one batch, and this will be very slow.
2. I noticed you use only use CPU for generation, is this just because the CPU is too slow compared to the GPU? You can set `batchsize=1`, to check whether there is any output.

**Comment by ShreyaKhurana** [comment]
Thank you! This worked. It was loading about 900 sentences for generation in one batch and that took up all the RAM, which is why it was getting killed in the middle. 

But I see the generation is extremely slow for one sentence per batch on CPU, it's ~6 seconds. Is this reasonable?

**Comment by teslacool** [comment]
You can set --batch-size=128 or 64 to accelerate generation.
