### ISSUE TITLE
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.

### ISSUE THREAD

**Issue by echan00** [bert-nmt/bert-nmt#3]
Ran into the following error while training a BERT-fused NMT model:

```
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown                                                                              
  len(cache))
Traceback (most recent call last):
  File "train.py", line 315, in <module>
    cli_main()
  File "train.py", line 307, in cli_main
    nprocs=args.distributed_world_size,
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/eee/bert-nmt/train.py", line 274, in distributed_main
    main(args, init_distributed=True)
  File "/home/eee/bert-nmt/train.py", line 89, in main
    train(args, trainer, task, epoch_itr)
  File "/home/eee/bert-nmt/train.py", line 130, in train
    log_output = trainer.train_step(samples)
  File "/home/eee/bert-nmt/fairseq/trainer.py", line 289, in train_step
    raise e
  File "/home/eee/bert-nmt/fairseq/trainer.py", line 266, in train_step
    ignore_grad
  File "/home/eee/bert-nmt/fairseq/tasks/fairseq_task.py", line 232, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eee/bert-nmt/fairseq/criterions/label_smoothed_cross_entropy.py", line 38, in forward
    net_output = model(**sample['net_input'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 442, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eee/bert-nmt/fairseq/models/transformer.py", line 339, in forward
    bert_encoder_out, _ =  self.bert_encoder(bert_input, output_all_encoded_layers=True, attention_mask= 1. - bert_encoder_padding_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 325, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.
```

Should transformer.py line 339 be changed from:
`bert_encoder_out, _ =  self.bert_encoder(bert_input, output_all_encoded_layers=True, attention_mask= 1. - bert_encoder_padding_mask)`

to:
`bert_encoder_out, _ =  self.bert_encoder(bert_input, output_all_encoded_layers=True, attention_mask= ~bert_encoder_padding_mask)`

**Comment by echan00** [comment]
Based on google results, it seems like either downgrading from pytorch 1.2 to 1.1 OR using ~ operator will work. I will follow up with results.

**Comment by bert-nmt** [comment]
Yes, we use torch 1.0.0 for our all experiments and did not encounter this error.

**Comment by echan00** [comment]
using ~ operator will works
