### ISSUE TITLE
TyTypeError: __init__() missing 3 required positional arguments: 'bertencoder', 'berttokenizer', and 'mask_cls_sep'

### ISSUE THREAD

**Issue by Daisy-123** [bert-nmt/bert-nmt#39]
I trained lightconv model via fairseq . 
When I used it in bert nmt, I got this error . 
` (bertNMT) blue90211@AI02:~/Storage01/bert-nmt$ CUDA_VISIBLE_DEVICES=0 python train.py $DATAPATH -a $ARCH --optimizer adam --lr 0.0005 -s $src -t $tgt --label-smoothing 0.1 --dropout 0.3 --max-tokens 4000 --min-lr '1e-09' --lr-scheduler inverse_sqrt --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --max-update 150000 --warmup-updates 4000 --warmup-init-lr '1e-07' --adam-betas '(0.9,0.98)' --save-dir $SAVEDIR --share-all-embeddings $warmup --encoder-bert-dropout --encoder-bert-dropout-ratio $bedropout --bert-model-name bert-base-uncased | tee -a $SAVEDIR/training.log
Traceback (most recent call last):
Namespace(adam_betas='(0.9,0.98)', adam_eps=1e-08, adaptive_softmax_cutoff=None, adaptive_softmax_dropout=0, arch='lightconv', attention_dropout=0.0, bert_first=True, bert_gates=[1, 1, 1, 1, 1, 1], bert_model_name='bert-base-uncased', bert_output_layer=-1, bert_ratio=1.0, bucket_cap_mb=25, clip_norm=25, cpu=False, criterion='label_smoothed_cross_entropy', curriculum=0, data='databin/wmt17_enzh_join', dataset_impl='cached', ddp_backend='c10d', decoder_attention_heads=8, decoder_conv_dim=512, decoder_conv_type='dynamic', decoder_embed_dim=512, decoder_embed_path=None, decoder_ffn_embed_dim=2048, decoder_glu=True, decoder_input_dim=512, decoder_kernel_size_list=[3, 7, 15, 31, 31, 31], decoder_layers=6, decoder_learned_pos=False, decoder_no_bert=False, decoder_normalize_before=False, decoder_output_dim=512, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, dropout=0.3, encoder_attention_heads=8, encoder_bert_dropout=True, encoder_bert_dropout_ratio=0.5, encoder_bert_mixup=False, encoder_conv_dim=512, encoder_conv_type='dynamic', encoder_embed_dim=512, encoder_embed_path=None, encoder_ffn_embed_dim=2048, encoder_glu=True, encoder_kernel_size_list=[3, 7, 15, 31, 31, 31, 31], encoder_layers=7, encoder_learned_pos=False, encoder_normalize_before=False, encoder_ratio=1.0, find_unused_parameters=False, finetune_bert=False, fix_batches_to_gpus=False, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, input_dropout=0.1, keep_interval_updates=-1, keep_last_epochs=-1, label_smoothing=0.1, lazy_load=False, left_pad_source='True', left_pad_target='False', log_format=None, log_interval=1000, lr=[0.0005], lr_scheduler='inverse_sqrt', mask_cls_sep=False, max_epoch=0, max_sentences=None, max_sentences_valid=None, max_source_positions=1024, max_target_positions=1024, max_tokens=4000, max_update=150000, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=1e-09, no_epoch_checkpoints=False, no_progress_bar=False, no_save=False, no_token_positional_embeddings=False, num_workers=0, optimizer='adam', optimizer_overrides='{}', raw_text=False, relu_dropout=0.0, required_batch_size_multiple=8, reset_dataloader=False, reset_lr_scheduler=True, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', save_dir='checkpoints', save_interval=1, save_interval_updates=0, seed=1, sentence_avg=False, share_all_embeddings=True, share_decoder_input_output_embed=False, skip_invalid_size_inputs_valid_test=False, source_lang='en', target_lang='zh', task='translation', tbmf_wrapper=False, tensorboard_logdir='', threshold_loss_scale=None, train_subset='train', update_freq=[1], upsample_primary=1, user_dir=None, valid_subset='valid', validate_interval=1, warmup_from_nmt=True, warmup_init_lr=1e-07, warmup_nmt_file='checkpoint_nmt.pt', warmup_updates=4000, weight_decay=0.0001, weight_dropout=0.0, weight_softmax=True)
| [en] dictionary: 73104 types
| [zh] dictionary: 73104 types
| databin/wmt17_enzh_join valid en-zh 2001 examples
  File "train.py", line 315, in <module>
    cli_main()
  File "train.py", line 311, in cli_main
    main(args)
  File "train.py", line 49, in main
    model = task.build_model(args)
  File "/mnt/Storage01/blue90211/bert-nmt/fairseq/tasks/fairseq_task.py", line 169, in build_model
    return models.build_model(args, self)
  File "/mnt/Storage01/blue90211/bert-nmt/fairseq/models/__init__.py", line 50, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
  File "/mnt/Storage01/blue90211/bert-nmt/fairseq/models/lightconv.py", line 176, in build_model
    return LightConvModel(encoder, decoder)
  File "/mnt/Storage01/blue90211/bert-nmt/fairseq/models/lightconv.py", line 53, in __init__
    super().__init__(encoder, decoder)
TypeError: __init__() missing 3 required positional arguments: 'bertencoder', 'berttokenizer', and 'mask_cls_sep'`

**Comment by teslacool** [comment]
Please refer to https://github.com/bert-nmt/bert-nmt/blob/9f150dec8f4c2c51c623ac0635c407b443f672e5/fairseq/models/fairseq_model.py#L189

**Comment by Daisy-123** [comment]
I seems to only transformer model can be used.  
If  I want to use lightconv model , I need to rewrite the lightconv.py script.
So I tried to edit encode layer refer to transformer.py , it works !
But decoder layer got some error like :
```
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/blue90211/anaconda3/envs/bertNMT/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/mnt/Storage01/blue90211/bert-nmt/train.py", line 274, in distributed_main
    main(args, init_distributed=True)
  File "/mnt/Storage01/blue90211/bert-nmt/train.py", line 89, in main
    train(args, trainer, task, epoch_itr)
  File "/mnt/Storage01/blue90211/bert-nmt/train.py", line 130, in train
    log_output = trainer.train_step(samples)
  File "/mnt/Storage01/blue90211/bert-nmt/fairseq/trainer.py", line 266, in train_step
    ignore_grad
  File "/mnt/Storage01/blue90211/bert-nmt/fairseq/tasks/fairseq_task.py", line 232, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/blue90211/anaconda3/envs/bertNMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Storage01/blue90211/bert-nmt/fairseq/criterions/label_smoothed_cross_entropy.py", line 38, in forward
    net_output = model(**sample['net_input'])
  File "/home/blue90211/anaconda3/envs/bertNMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Storage01/blue90211/bert-nmt/fairseq/legacy_distributed_data_parallel.py", line 78, in forward
    return self.module(*inputs, **kwargs)
  File "/home/blue90211/anaconda3/envs/bertNMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Storage01/blue90211/bert-nmt/fairseq/models/fairseq_model.py", line 252, in forward
    decoder_out = self.decoder(prev_output_tokens, encoder_out=encoder_out, bert_encoder_out=bert_encoder_out, **kwargs)
  File "/home/blue90211/anaconda3/envs/bertNMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Storage01/blue90211/bert-nmt/fairseq/models/lightconv.py", line 431, in forward
    incremental_state,
  File "/home/blue90211/anaconda3/envs/bertNMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Storage01/blue90211/bert-nmt/fairseq/models/lightconv.py", line 661, in forward
    self.conv._set_input_buffer(incremental_state, prev_conv_state)
  File "/mnt/Storage01/blue90211/bert-nmt/fairseq/modules/dynamic_convolution.py", line 214, in _set_input_buffer
    return utils.set_incremental_state(self, incremental_state, 'input_buffer', new_buffer)
  File "/mnt/Storage01/blue90211/bert-nmt/fairseq/utils.py", line 82, in set_incremental_state
    incremental_state[full_key] = value
IndexError: too many indices for tensor of dimension 3
```
Can you give me some suggestions ?  Thank you .
