### ISSUE TITLE
Fairseq repository download position

### ISSUE THREAD

**Issue by dsj96** [bert-nmt/bert-nmt#72]
# Train a vanilla NMT model using [Fairseq](https://github.com/pytorch/fairseq)
Using data above and standard [Fairseq](https://github.com/pytorch/fairseq) repository, you can get a pretrained NMT model.

The version should be a8f28ecb63ee01c33ea9f6986102136743d47ec2.
```
git clone https://github.com/pytorch/fairseq
git checkout a8f28ecb63ee01c33ea9f6986102136743d47ec2
```
----------------------------------------------------------------------------------------------------------------------------------------------
Hello bert-nmt! I saw a ```fairseq``` file in this project. When I down load the standard [Fairseq](https://github.com/pytorch/fairseq) repository and change a new branch ```a8f28ecb63ee01c33ea9f6986102136743d47ec2```, where should I put this repository? I'm not very clear about the relationship between these two documents.

**Comment by dsj96** [comment]
And I met a bug when run the following command. I checked some methods but didn't know how to deal with it. Could you give me some advice?
```
cd ../../..
TEXT=examples/translation/iwslt14.tokenized.de-en
src=de
tgt=en
destdir=iwslt_${src}_${tgt}
python preprocess.py --source-lang $src --target-lang $tgt \
  --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test \
  --destdir $destdir  --joined-dictionary --bert-model-name bert-base-german-dbmdz-uncased
```
log:
```
Namespace(no_progress_bar=False, log_interval=1000, log_format=None, tensorboard_logdir='', tbmf_wrapper=False, seed=1, cpu=False, fp16=False, memory_efficient_fp16=False, fp16_init_scale=128, fp16_scale_window=None, fp16_scale_tolerance=0.0, min_loss_scale=0.0001, threshold_loss_scale=None, user_dir=None, criterion='cross_entropy', optimizer='nag', lr_scheduler='fixed', task='translation', source_lang='de', target_lang='en', trainpref='examples/translation/iwslt14.tokenized.de-en/train', validpref='examples/translation/iwslt14.tokenized.de-en/valid', testpref='examples/translation/iwslt14.tokenized.de-en/test', destdir='iwslt_de_en', thresholdtgt=0, thresholdsrc=0, tgtdict=None, srcdict=None, nwordstgt=-1, nwordssrc=-1, alignfile=None, dataset_impl='cached', joined_dictionary=True, only_source=False, padding_factor=8, workers=1, bert_model_name='bert-base-german-dbmdz-uncased')
dsj1 dict_path(args.source_lang):  iwslt_de_en\dict.de.txt
dsj2 dict_path(args.target_lang):  iwslt_de_en\dict.en.txt
pkl_file write over!
| [de] Dictionary: 10151 types
| [de] examples/translation/iwslt14.tokenized.de-en/train.de: 160250 sents, 4034263 tokens, 0.0% replaced by <unk>
pkl_file write over!
| [de] Dictionary: 10151 types
| [de] examples/translation/iwslt14.tokenized.de-en/valid.de: 7284 sents, 185522 tokens, 0.000539% replaced by <unk>
pkl_file write over!
| [de] Dictionary: 10151 types
| [de] examples/translation/iwslt14.tokenized.de-en/test.de: 6750 sents, 161890 tokens, 0.029% replaced by <unk>
pkl_file write over!
| [en] Dictionary: 10151 types
| [en] examples/translation/iwslt14.tokenized.de-en/train.en: 160250 sents, 3946310 tokens, 0.0% replaced by <unk>
pkl_file write over!
| [en] Dictionary: 10151 types
| [en] examples/translation/iwslt14.tokenized.de-en/valid.en: 7284 sents, 182023 tokens, 0.000549% replaced by <unk>
pkl_file write over!
| [en] Dictionary: 10151 types
| [en] examples/translation/iwslt14.tokenized.de-en/test.en: 6750 sents, 156957 tokens, 0.00319% replaced by <unk>
Traceback (most recent call last):
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-german-dbmdz-uncased/resolve/main/tokenizer_config.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python-idea-workspace\bert-nmt\preprocess.py", line 287, in <module>
    cli_main()
  File "D:\python-idea-workspace\bert-nmt\preprocess.py", line 283, in cli_main
    main(args)
  File "D:\python-idea-workspace\bert-nmt\preprocess.py", line 203, in main
    berttokenizer = AutoTokenizer.from_pretrained(args.bert_model_name)
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 549, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 401, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\transformers\utils\hub.py", line 408, in cached_file
    resolved_file = hf_hub_download(
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\huggingface_hub-0.9.1-py3.8.egg\huggingface_hub\file_download.py", line 1089, in hf_hub_download
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\huggingface_hub-0.9.1-py3.8.egg\huggingface_hub\file_download.py", line 421, in _request_wrapper
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\huggingface_hub-0.9.1-py3.8.egg\huggingface_hub\file_download.py", line 460, in _request_wrapper
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\software-installment\Anaconda\envs\pytorch-gpu\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-german-dbmdz-uncased/resolve/main/tokenizer_config.json (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
```

**Comment by HymavathiG2712** [comment]
git clone https://github.com/pytorch/fairseq
git checkout a8f28ecb63ee01c33ea9f6986102136743d47ec2


You need to down the 0.9.0 version of fairseq
