### ISSUE TITLE
RuntimeError: index out of range: Tried to access index 512 out of table with 511 rows.

### ISSUE THREAD

**Issue by echan00** [bert-nmt/bert-nmt#8]
I am receiving the error `RuntimeError: index out of range: Tried to access index 512 out of table with 511 rows.` for translation of long sentences (full stack trace attached below). 
It looks like a sample with 329 src_tokens requires a bert_input tensor of length 568 that is too big.
What can I do to increase this source sentence length constraint?

```
{'net_input': 
  {
    'src_tokens': tensor([[   38,     6,     5,    34,     5,    ...]]), 
    'src_lengths': tensor([329]),
    'bert_input': tensor([[   101,  10105,    167,    115,  12100,   ...]])
  }
}
```
src_tokens' tensor length is 329
'bert_input' tensor length is 568

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/erikchan/Workspace/nda-ai/postedit_models/tf-serving/flask_app/app/main.py", line 52, in tagatag_v2
    outputs = translate_v2(inputs, src_id, targ_id, TAGATAG_MODELS, args, utils, src_dict, tgt_dict)
  File "/Users/erikchan/Workspace/nda-ai/postedit_models/tf-serving/flask_app/app/query_tagatag_v2.py", line 58, in translate_v2
    translations = task.inference_step(generator, TAGATAG_MODELS, sample)
  File "/Users/erikchan/Workspace/nda-ai/postedit_models/tf-serving/flask_app/app/fairseq/tasks/fairseq_task.py", line 246, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/usr/local/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/Users/erikchan/Workspace/nda-ai/postedit_models/tf-serving/flask_app/app/fairseq/sequence_generator.py", line 152, in generate
    bert_outs, _ = model.models[0].bert_encoder(bertinput, output_all_encoded_layers=True, attention_mask=~bert_encoder_padding_mask)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/erikchan/Workspace/nda-ai/postedit_models/tf-serving/flask_app/app/bert/modeling.py", line 736, in forward
    embedding_output = self.embeddings(input_ids, token_type_ids)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/erikchan/Workspace/nda-ai/postedit_models/tf-serving/flask_app/app/bert/modeling.py", line 272, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range: Tried to access index 512 out of table with 511 rows. at ../aten/src/TH/generic/THTensorEvenMoreMath.cpp:418
```

**Comment by bert-nmt** [comment]
I have constrained this bert_input at [line](https://github.com/bert-nmt/bert-nmt/blob/75bd2120a0302c6ae413a58276a2c0759a19287c/fairseq/binarizer.py#L47), and this error should not happen if you use my `preprocess.py`.

Because bert model has been pre-trained with this constraint, we should better keep this consistency.

**Comment by echan00** [comment]
Thanks @bert-nmt,  I was using your version of `preprocess.py` and was still getting the error.

Yes, my guess was to keep consistency with the bert model.
